# Generated by Django 5.2.7 on 2025-11-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventFlex_app', '0002_transaction_application_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='availability',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='application',
            name='expected_compensation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='application',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='application',
            name='portfolio_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='application',
            name='previous_events',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='relevant_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='why_interested',
            field=models.TextField(blank=True),
        ),
    ]
