# Generated by Django 5.2.7 on 2025-11-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventFlex_app', '0003_application_availability_application_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='expected_compensation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='experience_years',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
