# Generated by Django 5.2.7 on 2025-11-07 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventFlex_app', '0004_alter_application_expected_compensation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutocompleteSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('event_type', 'Event Type'), ('role', 'Role/Position'), ('skills', 'Skills'), ('location', 'Location'), ('requirements', 'Requirements'), ('city', 'City'), ('previous_events', 'Previous Events')], max_length=50)),
                ('value', models.CharField(max_length=500)),
                ('usage_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EventFlex_app.userprofile')),
            ],
            options={
                'ordering': ['-usage_count', '-updated_at'],
                'unique_together': {('field_type', 'value')},
            },
        ),
    ]
