# Generated by Django 5.2.7 on 2025-11-07 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventFlex_app', '0005_autocompletesuggestion'),
    ]

    operations = [
    ]
