# Generated by Django 5.2.7 on 2025-11-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventFlex_app', '0006_auto_20251107_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_rating_details',
            field=models.TextField(blank=True),
        ),
    ]
