# Generated by Django 5.2.7 on 2025-11-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventFlex_app', '0009_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='role',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
