# Generated by Django 5.2.7 on 2025-11-07 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventFlex_app', '0012_userprofile_bank_account_holder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('address', models.TextField()),
                ('document_type', models.CharField(choices=[('aadhar', 'Aadhar Card'), ('pan', 'PAN Card'), ('voter_id', 'Voter ID'), ('driving_license', 'Driving License'), ('passport', 'Passport')], max_length=50)),
                ('document_number', models.CharField(max_length=100)),
                ('document_front', models.TextField(blank=True)),
                ('document_back', models.TextField(blank=True)),
                ('selfie_photo', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=32)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=100)),
                ('years_of_experience', models.CharField(blank=True, max_length=50)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('previous_companies', models.TextField(blank=True)),
                ('certifications', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to='EventFlex_app.userprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
