# Generated by Django 5.2.7 on 2025-11-08 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventFlex_app', '0013_verificationdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_events_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='badge',
            field=models.CharField(choices=[('rising_star', 'Rising Star'), ('pro', 'Pro'), ('elite', 'Elite')], default='rising_star', max_length=32),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('review_text', models.TextField(blank=True)),
                ('professionalism', models.PositiveIntegerField(default=5)),
                ('punctuality', models.PositiveIntegerField(default=5)),
                ('quality_of_work', models.PositiveIntegerField(default=5)),
                ('communication', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='EventFlex_app.job')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to='EventFlex_app.userprofile')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to='EventFlex_app.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('job', 'staff', 'organizer')},
            },
        ),
    ]
